# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 170a4dac7a7fc9a13cda40279833bbcbd0674a962a77baf85087579ae5053b03d7f2e2825f838efdea1c0398c09ee23d16da1259652e8b602e20b750907e5efc

test:
  secret_key_base: 19f71fa4f13a9bb5aa3e5b46f366ce42ba7ed47da577a16035458266fd8cb8424ec7e5a15f22609510912e0e82817306400bc54de41304b4fbe7ceb22833a384

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
